<?xml version="1.0" encoding="utf-8"?><Database Name="Microproyecto" Class="DBLibraryEntityDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-J96M7O62;Initial Catalog=Microproyecto;Integrated Security=True" SettingsObjectName="Datos.Properties.Settings" SettingsPropertyName="MicroproyectoConnectionString" Provider="System.Data.SqlClient" />
</Database>