#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.DBConexion
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Microproyecto")]
	public partial class DBLibraryEntityDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insert_HabitacionXMotel(_HabitacionXMotel instance);
    partial void Update_HabitacionXMotel(_HabitacionXMotel instance);
    partial void Delete_HabitacionXMotel(_HabitacionXMotel instance);
    partial void InsertTipo_Habitacion(Tipo_Habitacion instance);
    partial void UpdateTipo_Habitacion(Tipo_Habitacion instance);
    partial void DeleteTipo_Habitacion(Tipo_Habitacion instance);
    partial void InsertFormas_de_pago(Formas_de_pago instance);
    partial void UpdateFormas_de_pago(Formas_de_pago instance);
    partial void DeleteFormas_de_pago(Formas_de_pago instance);
    partial void InsertFormas_de_pagoXMotele(Formas_de_pagoXMotele instance);
    partial void UpdateFormas_de_pagoXMotele(Formas_de_pagoXMotele instance);
    partial void DeleteFormas_de_pagoXMotele(Formas_de_pagoXMotele instance);
    partial void InsertLista_Usuario(Lista_Usuario instance);
    partial void UpdateLista_Usuario(Lista_Usuario instance);
    partial void DeleteLista_Usuario(Lista_Usuario instance);
    partial void InsertLogMantenimiento_Tabla(LogMantenimiento_Tabla instance);
    partial void UpdateLogMantenimiento_Tabla(LogMantenimiento_Tabla instance);
    partial void DeleteLogMantenimiento_Tabla(LogMantenimiento_Tabla instance);
    partial void InsertMotele(Motele instance);
    partial void UpdateMotele(Motele instance);
    partial void DeleteMotele(Motele instance);
    partial void InsertPuntuacion(Puntuacion instance);
    partial void UpdatePuntuacion(Puntuacion instance);
    partial void DeletePuntuacion(Puntuacion instance);
    partial void InsertResenas_Motel(Resenas_Motel instance);
    partial void UpdateResenas_Motel(Resenas_Motel instance);
    partial void DeleteResenas_Motel(Resenas_Motel instance);
    partial void InsertSectore(Sectore instance);
    partial void UpdateSectore(Sectore instance);
    partial void DeleteSectore(Sectore instance);
    #endregion
		
		public DBLibraryEntityDataContext() : 
				base(global::Datos.Properties.Settings.Default.MicroproyectoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBLibraryEntityDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBLibraryEntityDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBLibraryEntityDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBLibraryEntityDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<_HabitacionXMotel> _HabitacionXMotels
		{
			get
			{
				return this.GetTable<_HabitacionXMotel>();
			}
		}
		
		public System.Data.Linq.Table<Tipo_Habitacion> Tipo_Habitacions
		{
			get
			{
				return this.GetTable<Tipo_Habitacion>();
			}
		}
		
		public System.Data.Linq.Table<Formas_de_pago> Formas_de_pagos
		{
			get
			{
				return this.GetTable<Formas_de_pago>();
			}
		}
		
		public System.Data.Linq.Table<Formas_de_pagoXMotele> Formas_de_pagoXMoteles
		{
			get
			{
				return this.GetTable<Formas_de_pagoXMotele>();
			}
		}
		
		public System.Data.Linq.Table<Lista_Usuario> Lista_Usuarios
		{
			get
			{
				return this.GetTable<Lista_Usuario>();
			}
		}
		
		public System.Data.Linq.Table<LogMantenimiento_Tabla> LogMantenimiento_Tablas
		{
			get
			{
				return this.GetTable<LogMantenimiento_Tabla>();
			}
		}
		
		public System.Data.Linq.Table<Motele> Moteles
		{
			get
			{
				return this.GetTable<Motele>();
			}
		}
		
		public System.Data.Linq.Table<Puntuacion> Puntuacions
		{
			get
			{
				return this.GetTable<Puntuacion>();
			}
		}
		
		public System.Data.Linq.Table<Resenas_Motel> Resenas_Motels
		{
			get
			{
				return this.GetTable<Resenas_Motel>();
			}
		}
		
		public System.Data.Linq.Table<Sectore> Sectores
		{
			get
			{
				return this.GetTable<Sectore>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[ HabitacionXMotel]")]
	public partial class _HabitacionXMotel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_TipoHabitacionXModel;
		
		private int _ID_TipoHabitacion;
		
		private int _ID_Motel;
		
		private decimal _Precio;
		
		private EntityRef<Tipo_Habitacion> _Tipo_Habitacion;
		
		private EntityRef<Motele> _Motele;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_TipoHabitacionXModelChanging(int value);
    partial void OnID_TipoHabitacionXModelChanged();
    partial void OnID_TipoHabitacionChanging(int value);
    partial void OnID_TipoHabitacionChanged();
    partial void OnID_MotelChanging(int value);
    partial void OnID_MotelChanged();
    partial void OnPrecioChanging(decimal value);
    partial void OnPrecioChanged();
    #endregion
		
		public _HabitacionXMotel()
		{
			this._Tipo_Habitacion = default(EntityRef<Tipo_Habitacion>);
			this._Motele = default(EntityRef<Motele>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TipoHabitacionXModel", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_TipoHabitacionXModel
		{
			get
			{
				return this._ID_TipoHabitacionXModel;
			}
			set
			{
				if ((this._ID_TipoHabitacionXModel != value))
				{
					this.OnID_TipoHabitacionXModelChanging(value);
					this.SendPropertyChanging();
					this._ID_TipoHabitacionXModel = value;
					this.SendPropertyChanged("ID_TipoHabitacionXModel");
					this.OnID_TipoHabitacionXModelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TipoHabitacion", DbType="Int NOT NULL")]
		public int ID_TipoHabitacion
		{
			get
			{
				return this._ID_TipoHabitacion;
			}
			set
			{
				if ((this._ID_TipoHabitacion != value))
				{
					if (this._Tipo_Habitacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_TipoHabitacionChanging(value);
					this.SendPropertyChanging();
					this._ID_TipoHabitacion = value;
					this.SendPropertyChanged("ID_TipoHabitacion");
					this.OnID_TipoHabitacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Motel", DbType="Int NOT NULL")]
		public int ID_Motel
		{
			get
			{
				return this._ID_Motel;
			}
			set
			{
				if ((this._ID_Motel != value))
				{
					if (this._Motele.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_MotelChanging(value);
					this.SendPropertyChanging();
					this._ID_Motel = value;
					this.SendPropertyChanged("ID_Motel");
					this.OnID_MotelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Money NOT NULL")]
		public decimal Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this.OnPrecioChanging(value);
					this.SendPropertyChanging();
					this._Precio = value;
					this.SendPropertyChanged("Precio");
					this.OnPrecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipo_Habitacion__HabitacionXMotel", Storage="_Tipo_Habitacion", ThisKey="ID_TipoHabitacion", OtherKey="ID_TipoHabitacion", IsForeignKey=true)]
		public Tipo_Habitacion Tipo_Habitacion
		{
			get
			{
				return this._Tipo_Habitacion.Entity;
			}
			set
			{
				Tipo_Habitacion previousValue = this._Tipo_Habitacion.Entity;
				if (((previousValue != value) 
							|| (this._Tipo_Habitacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tipo_Habitacion.Entity = null;
						previousValue._HabitacionXMotels.Remove(this);
					}
					this._Tipo_Habitacion.Entity = value;
					if ((value != null))
					{
						value._HabitacionXMotels.Add(this);
						this._ID_TipoHabitacion = value.ID_TipoHabitacion;
					}
					else
					{
						this._ID_TipoHabitacion = default(int);
					}
					this.SendPropertyChanged("Tipo_Habitacion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Motele__HabitacionXMotel", Storage="_Motele", ThisKey="ID_Motel", OtherKey="ID_Motel", IsForeignKey=true)]
		public Motele Motele
		{
			get
			{
				return this._Motele.Entity;
			}
			set
			{
				Motele previousValue = this._Motele.Entity;
				if (((previousValue != value) 
							|| (this._Motele.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Motele.Entity = null;
						previousValue._HabitacionXMotels.Remove(this);
					}
					this._Motele.Entity = value;
					if ((value != null))
					{
						value._HabitacionXMotels.Add(this);
						this._ID_Motel = value.ID_Motel;
					}
					else
					{
						this._ID_Motel = default(int);
					}
					this.SendPropertyChanged("Motele");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tipo_Habitacion")]
	public partial class Tipo_Habitacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_TipoHabitacion;
		
		private string _Tipo;
		
		private EntitySet<_HabitacionXMotel> @__HabitacionXMotels;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_TipoHabitacionChanging(int value);
    partial void OnID_TipoHabitacionChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    #endregion
		
		public Tipo_Habitacion()
		{
			this.@__HabitacionXMotels = new EntitySet<_HabitacionXMotel>(new Action<_HabitacionXMotel>(this.attach__HabitacionXMotels), new Action<_HabitacionXMotel>(this.detach__HabitacionXMotels));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TipoHabitacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_TipoHabitacion
		{
			get
			{
				return this._ID_TipoHabitacion;
			}
			set
			{
				if ((this._ID_TipoHabitacion != value))
				{
					this.OnID_TipoHabitacionChanging(value);
					this.SendPropertyChanging();
					this._ID_TipoHabitacion = value;
					this.SendPropertyChanged("ID_TipoHabitacion");
					this.OnID_TipoHabitacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipo_Habitacion__HabitacionXMotel", Storage="__HabitacionXMotels", ThisKey="ID_TipoHabitacion", OtherKey="ID_TipoHabitacion")]
		public EntitySet<_HabitacionXMotel> _HabitacionXMotels
		{
			get
			{
				return this.@__HabitacionXMotels;
			}
			set
			{
				this.@__HabitacionXMotels.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach__HabitacionXMotels(_HabitacionXMotel entity)
		{
			this.SendPropertyChanging();
			entity.Tipo_Habitacion = this;
		}
		
		private void detach__HabitacionXMotels(_HabitacionXMotel entity)
		{
			this.SendPropertyChanging();
			entity.Tipo_Habitacion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Formas_de_pago")]
	public partial class Formas_de_pago : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_Formas_de_Pago;
		
		private string _Efectivo;
		
		private string _Tarjeta;
		
		private string _Transferencia;
		
		private EntitySet<Formas_de_pagoXMotele> _Formas_de_pagoXMoteles;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_Formas_de_PagoChanging(int value);
    partial void Onid_Formas_de_PagoChanged();
    partial void OnEfectivoChanging(string value);
    partial void OnEfectivoChanged();
    partial void OnTarjetaChanging(string value);
    partial void OnTarjetaChanged();
    partial void OnTransferenciaChanging(string value);
    partial void OnTransferenciaChanged();
    #endregion
		
		public Formas_de_pago()
		{
			this._Formas_de_pagoXMoteles = new EntitySet<Formas_de_pagoXMotele>(new Action<Formas_de_pagoXMotele>(this.attach_Formas_de_pagoXMoteles), new Action<Formas_de_pagoXMotele>(this.detach_Formas_de_pagoXMoteles));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Formas_de_Pago", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_Formas_de_Pago
		{
			get
			{
				return this._id_Formas_de_Pago;
			}
			set
			{
				if ((this._id_Formas_de_Pago != value))
				{
					this.Onid_Formas_de_PagoChanging(value);
					this.SendPropertyChanging();
					this._id_Formas_de_Pago = value;
					this.SendPropertyChanged("id_Formas_de_Pago");
					this.Onid_Formas_de_PagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Efectivo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Efectivo
		{
			get
			{
				return this._Efectivo;
			}
			set
			{
				if ((this._Efectivo != value))
				{
					this.OnEfectivoChanging(value);
					this.SendPropertyChanging();
					this._Efectivo = value;
					this.SendPropertyChanged("Efectivo");
					this.OnEfectivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarjeta", DbType="NVarChar(50)")]
		public string Tarjeta
		{
			get
			{
				return this._Tarjeta;
			}
			set
			{
				if ((this._Tarjeta != value))
				{
					this.OnTarjetaChanging(value);
					this.SendPropertyChanging();
					this._Tarjeta = value;
					this.SendPropertyChanged("Tarjeta");
					this.OnTarjetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transferencia", DbType="NVarChar(50)")]
		public string Transferencia
		{
			get
			{
				return this._Transferencia;
			}
			set
			{
				if ((this._Transferencia != value))
				{
					this.OnTransferenciaChanging(value);
					this.SendPropertyChanging();
					this._Transferencia = value;
					this.SendPropertyChanged("Transferencia");
					this.OnTransferenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Formas_de_pago_Formas_de_pagoXMotele", Storage="_Formas_de_pagoXMoteles", ThisKey="id_Formas_de_Pago", OtherKey="id_Formas_de_Pago")]
		public EntitySet<Formas_de_pagoXMotele> Formas_de_pagoXMoteles
		{
			get
			{
				return this._Formas_de_pagoXMoteles;
			}
			set
			{
				this._Formas_de_pagoXMoteles.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Formas_de_pagoXMoteles(Formas_de_pagoXMotele entity)
		{
			this.SendPropertyChanging();
			entity.Formas_de_pago = this;
		}
		
		private void detach_Formas_de_pagoXMoteles(Formas_de_pagoXMotele entity)
		{
			this.SendPropertyChanging();
			entity.Formas_de_pago = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Formas_de_pagoXMoteles")]
	public partial class Formas_de_pagoXMotele : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Formas_de_pagoXMoteles;
		
		private int _id_Formas_de_Pago;
		
		private int _ID_Motel;
		
		private EntityRef<Formas_de_pago> _Formas_de_pago;
		
		private EntityRef<Motele> _Motele;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_Formas_de_pagoXMotelesChanging(int value);
    partial void OnID_Formas_de_pagoXMotelesChanged();
    partial void Onid_Formas_de_PagoChanging(int value);
    partial void Onid_Formas_de_PagoChanged();
    partial void OnID_MotelChanging(int value);
    partial void OnID_MotelChanged();
    #endregion
		
		public Formas_de_pagoXMotele()
		{
			this._Formas_de_pago = default(EntityRef<Formas_de_pago>);
			this._Motele = default(EntityRef<Motele>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Formas_de_pagoXMoteles", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Formas_de_pagoXMoteles
		{
			get
			{
				return this._ID_Formas_de_pagoXMoteles;
			}
			set
			{
				if ((this._ID_Formas_de_pagoXMoteles != value))
				{
					this.OnID_Formas_de_pagoXMotelesChanging(value);
					this.SendPropertyChanging();
					this._ID_Formas_de_pagoXMoteles = value;
					this.SendPropertyChanged("ID_Formas_de_pagoXMoteles");
					this.OnID_Formas_de_pagoXMotelesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Formas_de_Pago", DbType="Int NOT NULL")]
		public int id_Formas_de_Pago
		{
			get
			{
				return this._id_Formas_de_Pago;
			}
			set
			{
				if ((this._id_Formas_de_Pago != value))
				{
					if (this._Formas_de_pago.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_Formas_de_PagoChanging(value);
					this.SendPropertyChanging();
					this._id_Formas_de_Pago = value;
					this.SendPropertyChanged("id_Formas_de_Pago");
					this.Onid_Formas_de_PagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Motel", DbType="Int NOT NULL")]
		public int ID_Motel
		{
			get
			{
				return this._ID_Motel;
			}
			set
			{
				if ((this._ID_Motel != value))
				{
					if (this._Motele.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_MotelChanging(value);
					this.SendPropertyChanging();
					this._ID_Motel = value;
					this.SendPropertyChanged("ID_Motel");
					this.OnID_MotelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Formas_de_pago_Formas_de_pagoXMotele", Storage="_Formas_de_pago", ThisKey="id_Formas_de_Pago", OtherKey="id_Formas_de_Pago", IsForeignKey=true)]
		public Formas_de_pago Formas_de_pago
		{
			get
			{
				return this._Formas_de_pago.Entity;
			}
			set
			{
				Formas_de_pago previousValue = this._Formas_de_pago.Entity;
				if (((previousValue != value) 
							|| (this._Formas_de_pago.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Formas_de_pago.Entity = null;
						previousValue.Formas_de_pagoXMoteles.Remove(this);
					}
					this._Formas_de_pago.Entity = value;
					if ((value != null))
					{
						value.Formas_de_pagoXMoteles.Add(this);
						this._id_Formas_de_Pago = value.id_Formas_de_Pago;
					}
					else
					{
						this._id_Formas_de_Pago = default(int);
					}
					this.SendPropertyChanged("Formas_de_pago");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Motele_Formas_de_pagoXMotele", Storage="_Motele", ThisKey="ID_Motel", OtherKey="ID_Motel", IsForeignKey=true)]
		public Motele Motele
		{
			get
			{
				return this._Motele.Entity;
			}
			set
			{
				Motele previousValue = this._Motele.Entity;
				if (((previousValue != value) 
							|| (this._Motele.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Motele.Entity = null;
						previousValue.Formas_de_pagoXMoteles.Remove(this);
					}
					this._Motele.Entity = value;
					if ((value != null))
					{
						value.Formas_de_pagoXMoteles.Add(this);
						this._ID_Motel = value.ID_Motel;
					}
					else
					{
						this._ID_Motel = default(int);
					}
					this.SendPropertyChanged("Motele");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lista_Usuario")]
	public partial class Lista_Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Usuario;
		
		private string _Nom_usuario;
		
		private string _Passwd;
		
		private string _Tipo_usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_UsuarioChanging(int value);
    partial void OnId_UsuarioChanged();
    partial void OnNom_usuarioChanging(string value);
    partial void OnNom_usuarioChanged();
    partial void OnPasswdChanging(string value);
    partial void OnPasswdChanged();
    partial void OnTipo_usuarioChanging(string value);
    partial void OnTipo_usuarioChanged();
    #endregion
		
		public Lista_Usuario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Usuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Usuario
		{
			get
			{
				return this._Id_Usuario;
			}
			set
			{
				if ((this._Id_Usuario != value))
				{
					this.OnId_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._Id_Usuario = value;
					this.SendPropertyChanged("Id_Usuario");
					this.OnId_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom_usuario", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nom_usuario
		{
			get
			{
				return this._Nom_usuario;
			}
			set
			{
				if ((this._Nom_usuario != value))
				{
					this.OnNom_usuarioChanging(value);
					this.SendPropertyChanging();
					this._Nom_usuario = value;
					this.SendPropertyChanged("Nom_usuario");
					this.OnNom_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Passwd", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Passwd
		{
			get
			{
				return this._Passwd;
			}
			set
			{
				if ((this._Passwd != value))
				{
					this.OnPasswdChanging(value);
					this.SendPropertyChanging();
					this._Passwd = value;
					this.SendPropertyChanged("Passwd");
					this.OnPasswdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo_usuario", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Tipo_usuario
		{
			get
			{
				return this._Tipo_usuario;
			}
			set
			{
				if ((this._Tipo_usuario != value))
				{
					this.OnTipo_usuarioChanging(value);
					this.SendPropertyChanging();
					this._Tipo_usuario = value;
					this.SendPropertyChanged("Tipo_usuario");
					this.OnTipo_usuarioChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LogMantenimiento_Tablas")]
	public partial class LogMantenimiento_Tabla : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_Tabla;
		
		private string _Usuario;
		
		private string _Descripcion_Mant;
		
		private System.DateTime _Fecha;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_TablaChanging(int value);
    partial void Onid_TablaChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnDescripcion_MantChanging(string value);
    partial void OnDescripcion_MantChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    #endregion
		
		public LogMantenimiento_Tabla()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Tabla", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_Tabla
		{
			get
			{
				return this._id_Tabla;
			}
			set
			{
				if ((this._id_Tabla != value))
				{
					this.Onid_TablaChanging(value);
					this.SendPropertyChanging();
					this._id_Tabla = value;
					this.SendPropertyChanged("id_Tabla");
					this.Onid_TablaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion_Mant", DbType="NVarChar(MAX)")]
		public string Descripcion_Mant
		{
			get
			{
				return this._Descripcion_Mant;
			}
			set
			{
				if ((this._Descripcion_Mant != value))
				{
					this.OnDescripcion_MantChanging(value);
					this.SendPropertyChanging();
					this._Descripcion_Mant = value;
					this.SendPropertyChanged("Descripcion_Mant");
					this.OnDescripcion_MantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Moteles")]
	public partial class Motele : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Motel;
		
		private string _Nombre;
		
		private string _Ubicacion;
		
		private int _ID_Calificacion;
		
		private int _ID_Sector;
		
		private EntitySet<_HabitacionXMotel> @__HabitacionXMotels;
		
		private EntitySet<Formas_de_pagoXMotele> _Formas_de_pagoXMoteles;
		
		private EntitySet<Puntuacion> _Puntuacions;
		
		private EntitySet<Resenas_Motel> _Resenas_Motels;
		
		private EntityRef<Sectore> _Sectore;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_MotelChanging(int value);
    partial void OnID_MotelChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnUbicacionChanging(string value);
    partial void OnUbicacionChanged();
    partial void OnID_CalificacionChanging(int value);
    partial void OnID_CalificacionChanged();
    partial void OnID_SectorChanging(int value);
    partial void OnID_SectorChanged();
    #endregion
		
		public Motele()
		{
			this.@__HabitacionXMotels = new EntitySet<_HabitacionXMotel>(new Action<_HabitacionXMotel>(this.attach__HabitacionXMotels), new Action<_HabitacionXMotel>(this.detach__HabitacionXMotels));
			this._Formas_de_pagoXMoteles = new EntitySet<Formas_de_pagoXMotele>(new Action<Formas_de_pagoXMotele>(this.attach_Formas_de_pagoXMoteles), new Action<Formas_de_pagoXMotele>(this.detach_Formas_de_pagoXMoteles));
			this._Puntuacions = new EntitySet<Puntuacion>(new Action<Puntuacion>(this.attach_Puntuacions), new Action<Puntuacion>(this.detach_Puntuacions));
			this._Resenas_Motels = new EntitySet<Resenas_Motel>(new Action<Resenas_Motel>(this.attach_Resenas_Motels), new Action<Resenas_Motel>(this.detach_Resenas_Motels));
			this._Sectore = default(EntityRef<Sectore>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Motel", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Motel
		{
			get
			{
				return this._ID_Motel;
			}
			set
			{
				if ((this._ID_Motel != value))
				{
					this.OnID_MotelChanging(value);
					this.SendPropertyChanging();
					this._ID_Motel = value;
					this.SendPropertyChanged("ID_Motel");
					this.OnID_MotelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ubicacion", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Ubicacion
		{
			get
			{
				return this._Ubicacion;
			}
			set
			{
				if ((this._Ubicacion != value))
				{
					this.OnUbicacionChanging(value);
					this.SendPropertyChanging();
					this._Ubicacion = value;
					this.SendPropertyChanged("Ubicacion");
					this.OnUbicacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Calificacion", DbType="Int NOT NULL")]
		public int ID_Calificacion
		{
			get
			{
				return this._ID_Calificacion;
			}
			set
			{
				if ((this._ID_Calificacion != value))
				{
					this.OnID_CalificacionChanging(value);
					this.SendPropertyChanging();
					this._ID_Calificacion = value;
					this.SendPropertyChanged("ID_Calificacion");
					this.OnID_CalificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Sector", DbType="Int NOT NULL")]
		public int ID_Sector
		{
			get
			{
				return this._ID_Sector;
			}
			set
			{
				if ((this._ID_Sector != value))
				{
					if (this._Sectore.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_SectorChanging(value);
					this.SendPropertyChanging();
					this._ID_Sector = value;
					this.SendPropertyChanged("ID_Sector");
					this.OnID_SectorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Motele__HabitacionXMotel", Storage="__HabitacionXMotels", ThisKey="ID_Motel", OtherKey="ID_Motel")]
		public EntitySet<_HabitacionXMotel> _HabitacionXMotels
		{
			get
			{
				return this.@__HabitacionXMotels;
			}
			set
			{
				this.@__HabitacionXMotels.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Motele_Formas_de_pagoXMotele", Storage="_Formas_de_pagoXMoteles", ThisKey="ID_Motel", OtherKey="ID_Motel")]
		public EntitySet<Formas_de_pagoXMotele> Formas_de_pagoXMoteles
		{
			get
			{
				return this._Formas_de_pagoXMoteles;
			}
			set
			{
				this._Formas_de_pagoXMoteles.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Motele_Puntuacion", Storage="_Puntuacions", ThisKey="ID_Motel", OtherKey="ID_Motel")]
		public EntitySet<Puntuacion> Puntuacions
		{
			get
			{
				return this._Puntuacions;
			}
			set
			{
				this._Puntuacions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Motele_Resenas_Motel", Storage="_Resenas_Motels", ThisKey="ID_Motel", OtherKey="ID_Motel")]
		public EntitySet<Resenas_Motel> Resenas_Motels
		{
			get
			{
				return this._Resenas_Motels;
			}
			set
			{
				this._Resenas_Motels.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sectore_Motele", Storage="_Sectore", ThisKey="ID_Sector", OtherKey="ID_Sector", IsForeignKey=true)]
		public Sectore Sectore
		{
			get
			{
				return this._Sectore.Entity;
			}
			set
			{
				Sectore previousValue = this._Sectore.Entity;
				if (((previousValue != value) 
							|| (this._Sectore.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sectore.Entity = null;
						previousValue.Moteles.Remove(this);
					}
					this._Sectore.Entity = value;
					if ((value != null))
					{
						value.Moteles.Add(this);
						this._ID_Sector = value.ID_Sector;
					}
					else
					{
						this._ID_Sector = default(int);
					}
					this.SendPropertyChanged("Sectore");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach__HabitacionXMotels(_HabitacionXMotel entity)
		{
			this.SendPropertyChanging();
			entity.Motele = this;
		}
		
		private void detach__HabitacionXMotels(_HabitacionXMotel entity)
		{
			this.SendPropertyChanging();
			entity.Motele = null;
		}
		
		private void attach_Formas_de_pagoXMoteles(Formas_de_pagoXMotele entity)
		{
			this.SendPropertyChanging();
			entity.Motele = this;
		}
		
		private void detach_Formas_de_pagoXMoteles(Formas_de_pagoXMotele entity)
		{
			this.SendPropertyChanging();
			entity.Motele = null;
		}
		
		private void attach_Puntuacions(Puntuacion entity)
		{
			this.SendPropertyChanging();
			entity.Motele = this;
		}
		
		private void detach_Puntuacions(Puntuacion entity)
		{
			this.SendPropertyChanging();
			entity.Motele = null;
		}
		
		private void attach_Resenas_Motels(Resenas_Motel entity)
		{
			this.SendPropertyChanging();
			entity.Motele = this;
		}
		
		private void detach_Resenas_Motels(Resenas_Motel entity)
		{
			this.SendPropertyChanging();
			entity.Motele = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Puntuacion")]
	public partial class Puntuacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Calificacion;
		
		private int _ID_Motel;
		
		private System.DateTime _Fecha;
		
		private int _Calificacion;
		
		private EntityRef<Motele> _Motele;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CalificacionChanging(int value);
    partial void OnID_CalificacionChanged();
    partial void OnID_MotelChanging(int value);
    partial void OnID_MotelChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    partial void OnCalificacionChanging(int value);
    partial void OnCalificacionChanged();
    #endregion
		
		public Puntuacion()
		{
			this._Motele = default(EntityRef<Motele>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Calificacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Calificacion
		{
			get
			{
				return this._ID_Calificacion;
			}
			set
			{
				if ((this._ID_Calificacion != value))
				{
					this.OnID_CalificacionChanging(value);
					this.SendPropertyChanging();
					this._ID_Calificacion = value;
					this.SendPropertyChanged("ID_Calificacion");
					this.OnID_CalificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Motel", DbType="Int NOT NULL")]
		public int ID_Motel
		{
			get
			{
				return this._ID_Motel;
			}
			set
			{
				if ((this._ID_Motel != value))
				{
					if (this._Motele.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_MotelChanging(value);
					this.SendPropertyChanging();
					this._ID_Motel = value;
					this.SendPropertyChanged("ID_Motel");
					this.OnID_MotelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Calificacion", DbType="Int NOT NULL")]
		public int Calificacion
		{
			get
			{
				return this._Calificacion;
			}
			set
			{
				if ((this._Calificacion != value))
				{
					this.OnCalificacionChanging(value);
					this.SendPropertyChanging();
					this._Calificacion = value;
					this.SendPropertyChanged("Calificacion");
					this.OnCalificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Motele_Puntuacion", Storage="_Motele", ThisKey="ID_Motel", OtherKey="ID_Motel", IsForeignKey=true)]
		public Motele Motele
		{
			get
			{
				return this._Motele.Entity;
			}
			set
			{
				Motele previousValue = this._Motele.Entity;
				if (((previousValue != value) 
							|| (this._Motele.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Motele.Entity = null;
						previousValue.Puntuacions.Remove(this);
					}
					this._Motele.Entity = value;
					if ((value != null))
					{
						value.Puntuacions.Add(this);
						this._ID_Motel = value.ID_Motel;
					}
					else
					{
						this._ID_Motel = default(int);
					}
					this.SendPropertyChanged("Motele");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Resenas_Motel")]
	public partial class Resenas_Motel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_ReseñaMotel;
		
		private int _ID_Motel;
		
		private string _Reseña;
		
		private EntityRef<Motele> _Motele;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ReseñaMotelChanging(int value);
    partial void OnID_ReseñaMotelChanged();
    partial void OnID_MotelChanging(int value);
    partial void OnID_MotelChanged();
    partial void OnReseñaChanging(string value);
    partial void OnReseñaChanged();
    #endregion
		
		public Resenas_Motel()
		{
			this._Motele = default(EntityRef<Motele>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ReseñaMotel", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_ReseñaMotel
		{
			get
			{
				return this._ID_ReseñaMotel;
			}
			set
			{
				if ((this._ID_ReseñaMotel != value))
				{
					this.OnID_ReseñaMotelChanging(value);
					this.SendPropertyChanging();
					this._ID_ReseñaMotel = value;
					this.SendPropertyChanged("ID_ReseñaMotel");
					this.OnID_ReseñaMotelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Motel", DbType="Int NOT NULL")]
		public int ID_Motel
		{
			get
			{
				return this._ID_Motel;
			}
			set
			{
				if ((this._ID_Motel != value))
				{
					if (this._Motele.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_MotelChanging(value);
					this.SendPropertyChanging();
					this._ID_Motel = value;
					this.SendPropertyChanged("ID_Motel");
					this.OnID_MotelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reseña", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Reseña
		{
			get
			{
				return this._Reseña;
			}
			set
			{
				if ((this._Reseña != value))
				{
					this.OnReseñaChanging(value);
					this.SendPropertyChanging();
					this._Reseña = value;
					this.SendPropertyChanged("Reseña");
					this.OnReseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Motele_Resenas_Motel", Storage="_Motele", ThisKey="ID_Motel", OtherKey="ID_Motel", IsForeignKey=true)]
		public Motele Motele
		{
			get
			{
				return this._Motele.Entity;
			}
			set
			{
				Motele previousValue = this._Motele.Entity;
				if (((previousValue != value) 
							|| (this._Motele.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Motele.Entity = null;
						previousValue.Resenas_Motels.Remove(this);
					}
					this._Motele.Entity = value;
					if ((value != null))
					{
						value.Resenas_Motels.Add(this);
						this._ID_Motel = value.ID_Motel;
					}
					else
					{
						this._ID_Motel = default(int);
					}
					this.SendPropertyChanged("Motele");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sectores")]
	public partial class Sectore : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Sector;
		
		private string _Nombre_Sector;
		
		private EntitySet<Motele> _Moteles;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_SectorChanging(int value);
    partial void OnID_SectorChanged();
    partial void OnNombre_SectorChanging(string value);
    partial void OnNombre_SectorChanged();
    #endregion
		
		public Sectore()
		{
			this._Moteles = new EntitySet<Motele>(new Action<Motele>(this.attach_Moteles), new Action<Motele>(this.detach_Moteles));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Sector", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Sector
		{
			get
			{
				return this._ID_Sector;
			}
			set
			{
				if ((this._ID_Sector != value))
				{
					this.OnID_SectorChanging(value);
					this.SendPropertyChanging();
					this._ID_Sector = value;
					this.SendPropertyChanged("ID_Sector");
					this.OnID_SectorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Sector", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string Nombre_Sector
		{
			get
			{
				return this._Nombre_Sector;
			}
			set
			{
				if ((this._Nombre_Sector != value))
				{
					this.OnNombre_SectorChanging(value);
					this.SendPropertyChanging();
					this._Nombre_Sector = value;
					this.SendPropertyChanged("Nombre_Sector");
					this.OnNombre_SectorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sectore_Motele", Storage="_Moteles", ThisKey="ID_Sector", OtherKey="ID_Sector")]
		public EntitySet<Motele> Moteles
		{
			get
			{
				return this._Moteles;
			}
			set
			{
				this._Moteles.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Moteles(Motele entity)
		{
			this.SendPropertyChanging();
			entity.Sectore = this;
		}
		
		private void detach_Moteles(Motele entity)
		{
			this.SendPropertyChanging();
			entity.Sectore = null;
		}
	}
}
#pragma warning restore 1591
